"""
Code generated by Claude AI for this set up.
Converts an AEMOT raw-event log (.aemotevt) to Event Stream v2, dvs type
(.es), as read by github.com/neuromorphicsystems/event_stream and the wider
Prophesee/sepia ecosystem.

Two modes, selected with --split_tracks:
    (default) merge mode:
        All tracks are merged into ONE .es file, sorted by t. track_id is
        dropped entirely - .es has no field for it.
    --split_tracks:
        Each track_id gets its OWN .es file, written into a folder named
        after the input file (e.g. "mylog/3.es", "mylog/7.es", ...).
        Tracks with fewer than --min_events events are skipped entirely.
        Each track's timestamps are zeroed to that track's own first
        event (there's no shared reference point once tracks are split
        into independent files).

.aemotevt layout (must match raw_event_logger.hpp):
    RawEventLogFileHeader (24 bytes):
        char     magic[8]        "AEMOTEVT"
        uint32   version          (1)
        uint32   reserved
        uint32   record_size      (24)
        uint32   reserved2
    RawEventRecord (24 bytes), repeated:
        double   t          seconds, relative to the run's first event (t1)
        uint32   track_id   used to split/filter events, then dropped
        uint16   x
        uint16   y
        uint8    p          1 = ON, 0 = OFF
        uint8    reserved[7]

.es v2 dvs layout, confirmed against sepia.hpp
(github.com/neuromorphicsystems/event_stream/blob/main/sepia.hpp):
    Header (20 bytes):
        bytes    "Event Stream"   (12 ASCII bytes, no null terminator)
        uint8[3] version           [2, 0, 0]
        uint8    type              1 (dvs)
        uint16   width             little-endian
        uint16   height            little-endian
    Then each event, variable length:
        Zero or more 0xFF "overflow" bytes, each worth 127 time units of
        relative delta since the previous event's t.
        One final byte: (remaining_delta << 1) | polarity_bit
        uint16   x   little-endian
        uint16   y   little-endian
    Timestamps must be strictly monotonic non-decreasing - sepia's own
    encoder throws on a decrease, and this script asserts the same.

.es timestamps are integers (conventionally microseconds). This script
converts t (seconds, float) -> round(t * 1e6) (integer microseconds).
In merge mode, t=0 corresponds to the original log's first event (same
as the un-split behavior always has). In split mode, t=0 in each track's
file corresponds to THAT track's own first event.
"""

import argparse
import struct
import os
from collections import defaultdict

AEMOTEVT_HEADER_FMT = "<8sIIII"
AEMOTEVT_HEADER_SIZE = struct.calcsize(AEMOTEVT_HEADER_FMT)
AEMOTEVT_RECORD_FMT = "<dI2H B7x"   # t, track_id, x, y, p, then 7 pad/reserved bytes
AEMOTEVT_RECORD_SIZE = struct.calcsize(AEMOTEVT_RECORD_FMT)

ES_SIGNATURE = b"Event Stream"
ES_VERSION = bytes([2, 0, 0])
ES_TYPE_DVS = 1

OVERFLOW_BYTE = 0xFF
MAX_DELTA_PER_BYTE = 0b1111111  # 127 - see write_to_reference<type::dvs> in sepia.hpp


def read_aemotevt_by_track(path):
    """Reads the whole .aemotevt log and buckets records by track_id.

    Returns a dict: track_id -> list of (t_seconds, x, y, p) tuples, each
    list in original file order (so still non-decreasing in t).
    """

    print(f"[Info] Loading .aemotevt log from {path}...")

    tracks = defaultdict(list)
    total = 0

    with open(path, "rb") as f:
        header_bytes = f.read(AEMOTEVT_HEADER_SIZE)
        magic, version, _reserved, record_size, _reserved2 = struct.unpack(AEMOTEVT_HEADER_FMT, header_bytes)
        if magic != b"AEMOTEVT":
            raise ValueError(f"Unexpected magic bytes: {magic!r} - wrong file or format changed?")
        if record_size != AEMOTEVT_RECORD_SIZE:
            raise ValueError(
                f"record_size mismatch: header says {record_size}, "
                f"this script expects {AEMOTEVT_RECORD_SIZE} (version {version})."
            )

        while True:
            chunk = f.read(record_size)
            if len(chunk) < record_size:
                break
            t, track_id, x, y, p = struct.unpack(AEMOTEVT_RECORD_FMT, chunk)
            tracks[track_id].append((t, x, y, p))
            total += 1

    print(f"[Info] Loaded {total} events across {len(tracks)} track_id(s).")
    return tracks


def write_es_dvs(events, output_path, width, height, zero_to_first_event=False):
    """events: iterable of (t_seconds, x, y, p) in non-decreasing t order.
    Writes an Event Stream v2 dvs file to output_path.

    If zero_to_first_event is True, t=0 in the output corresponds to the
    first event in `events` (used for split-track files, which have no
    shared reference point). If False, t=0 corresponds to t_seconds==0
    as given (used for the merged file, matching legacy behavior)."""

    print(f"[Info] Writing .es file to {output_path}...")

    with open(output_path, "wb") as f:
        f.write(ES_SIGNATURE)
        f.write(ES_VERSION)
        f.write(bytes([ES_TYPE_DVS]))
        f.write(struct.pack("<H", width))
        f.write(struct.pack("<H", height))

        previous_t_us = 0
        count = 0
        t0_us = None
        for t_seconds, x, y, p in events:
            t_us = round(t_seconds * 1e6)

            if zero_to_first_event:
                if t0_us is None:
                    t0_us = t_us
                t_us -= t0_us

            if t_us < previous_t_us:
                raise ValueError(
                    f"non-monotonic timestamp at event {count}: {t_us}us follows {previous_t_us}us "
                    f"- .es requires strictly non-decreasing timestamps (matches sepia.hpp's own check)"
                )
            if x >= width or y >= height:
                raise ValueError(
                    f"event {count} at ({x},{y}) is outside the declared {width}x{height} "
                    f"frame - .es readers will reject this (coordinates_overflow in sepia.hpp)"
                )

            relative_t = t_us - previous_t_us
            while relative_t >= MAX_DELTA_PER_BYTE:
                f.write(bytes([OVERFLOW_BYTE]))
                relative_t -= MAX_DELTA_PER_BYTE

            on_bit = 1 if p else 0
            f.write(bytes([(relative_t << 1) | on_bit]))
            f.write(struct.pack("<H", x))
            f.write(struct.pack("<H", y))

            previous_t_us = t_us
            count += 1

    return count


def convert_split(aemotevt_path, output_dir, width, height, min_events):
    """Splits the log into one .es file per track_id inside output_dir."""

    tracks = read_aemotevt_by_track(aemotevt_path)

    os.makedirs(output_dir, exist_ok=True)

    written_tracks = 0
    written_events = 0
    skipped_tracks = 0
    skipped_events = 0

    for track_id in sorted(tracks.keys()):
        events = tracks[track_id]
        if len(events) < min_events:
            print(f"[Info] Skipping track_id {track_id}: only {len(events)} events (< min_events={min_events}).")
            skipped_tracks += 1
            skipped_events += len(events)
            continue

        output_path = os.path.join(output_dir, f"{track_id}.es")
        n = write_es_dvs(events, output_path, width, height, zero_to_first_event=True)
        print(f"[Info] Wrote track_id {track_id}: {n} events -> {output_path}")
        written_tracks += 1
        written_events += n

    print(
        f"[Info] Done. Wrote {written_tracks} track file(s) / {written_events} events to {output_dir}. "
        f"Skipped {skipped_tracks} small track(s) / {skipped_events} events (min_events={min_events})."
    )


def convert_merge(aemotevt_path, output_path, width, height):
    """Merges all tracks into a single .es file, sorted by t, track_id dropped."""

    tracks = read_aemotevt_by_track(aemotevt_path)

    all_events = []
    for track_id in sorted(tracks.keys()):
        all_events.extend(tracks[track_id])

    # Sort all events by timestamp to ensure monotonicity across tracks
    all_events.sort(key=lambda e: e[0])

    n = write_es_dvs(all_events, output_path, width, height, zero_to_first_event=False)
    print(f"[Info] Wrote merged .es file: {n} events -> {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("input", help="name of the .aemotevt raw-event log file inside the track_logs/ folder")
    parser.add_argument("--output", default=None,
                         help="merge mode: custom .es filename (extension added automatically if missing). "
                              "split mode: custom folder to hold the per-track .es files. "
                              "Defaults to a name/folder based on the input filename.")
    parser.add_argument("--width", type=int, default=1280, help="sensor width in pixels. Defaults to 1280 if not set")
    parser.add_argument("--height", type=int, default=720, help="sensor height in pixels. Defaults to 720 if not set")
    parser.add_argument("--min_events", type=int, default=100000,
                         help="split mode only: tracks with fewer than this many events are skipped. Defaults to 100000 if not set")
    parser.add_argument("--split_tracks", action="store_true",
                         help="if set, writes each track_id to its own .es file in a folder. "
                              "Otherwise, all events are merged into a single .es file. Defaults to False if not set")
    args = parser.parse_args()

    this_file_dir = os.path.dirname(os.path.abspath(__file__))
    aemotevt_path = os.path.join(this_file_dir, args.input + ".aemotevt")

    if args.split_tracks:
        output_dir = os.path.join(this_file_dir, args.input) if args.output is None else args.output
        convert_split(aemotevt_path, output_dir, args.width, args.height, args.min_events)
    else:
        if args.output is None:
            output_path = os.path.join(this_file_dir, args.input + ".es")
        else:
            output_path = args.output if args.output.endswith(".es") else args.output + ".es"
        convert_merge(aemotevt_path, output_path, args.width, args.height)