"""
Code generated by Claude AI for this set up.
Converts an AEMOT raw-event log (.aemotevt) to Event Stream v2, dvs type
(.es), as read by github.com/neuromorphicsystems/event_stream and the wider
Prophesee/sepia ecosystem. Only events belonging to ONE selected track_id
are kept - all other tracks are dropped. track_id itself is never written
out - .es has no field for it.

.aemotevt layout (must match raw_event_logger.hpp):
    RawEventLogFileHeader (24 bytes):
        char     magic[8]        "AEMOTEVT"
        uint32   version          (1)
        uint32   reserved
        uint32   record_size      (24)
        uint32   reserved2
    RawEventRecord (24 bytes), repeated:
        double   t          seconds, relative to the run's first event (t1)
        uint32   track_id   used to FILTER events in this conversion, then dropped
        uint16   x
        uint16   y
        uint8    p          1 = ON, 0 = OFF
        uint8    reserved[7]

.es v2 dvs layout, confirmed against sepia.hpp
(github.com/neuromorphicsystems/event_stream/blob/main/sepia.hpp):
    Header (20 bytes):
        bytes    "Event Stream"   (12 ASCII bytes, no null terminator)
        uint8[3] version           [2, 0, 0]
        uint8    type              1 (dvs)
        uint16   width             little-endian
        uint16   height            little-endian
    Then each event, variable length:
        Zero or more 0xFF "overflow" bytes, each worth 127 time units of
        relative delta since the previous event's t (this is how deltas
        >= 127 are encoded - not a single wider integer field).
        One final byte: (remaining_delta << 1) | polarity_bit
            (remaining_delta is 0-126, fits in the top 7 bits)
        uint16   x   little-endian
        uint16   y   little-endian
    Timestamps must be strictly monotonic non-decreasing - sepia's own
    encoder throws on a decrease, and this script asserts the same.
    IMPORTANT: because we now filter down to a single track_id, the
    remaining events are still emitted in original file order, so
    monotonicity is preserved automatically (we never reorder anything -
    we just skip records whose track_id doesn't match).

.es timestamps are integers (conventionally microseconds). This script
converts t (seconds, float) -> round(t * 1e6) (integer microseconds),
relative to the same t1-based zero point .aemotevt already uses - there's
no independent ".es epoch" to align to, so the .es file's t=0 will
correspond to the .aemotevt run's first event, same as today (i.e. still
relative to the very first event in the ORIGINAL multi-track file, not
the first event of the selected track).
"""

import argparse
import struct
import os

AEMOTEVT_HEADER_FMT = "<8sIIII"
AEMOTEVT_HEADER_SIZE = struct.calcsize(AEMOTEVT_HEADER_FMT)
AEMOTEVT_RECORD_FMT = "<dI2H B7x"   # t, track_id, x, y, p, then 7 pad/reserved bytes
AEMOTEVT_RECORD_SIZE = struct.calcsize(AEMOTEVT_RECORD_FMT)

ES_SIGNATURE = b"Event Stream"
ES_VERSION = bytes([2, 0, 0])
ES_TYPE_DVS = 1

OVERFLOW_BYTE = 0xFF
MAX_DELTA_PER_BYTE = 0b1111111  # 127 - see write_to_reference<type::dvs> in sepia.hpp


def read_aemotevt(path, track_id_filter=None):
    """Yields (t_seconds, x, y, p) tuples in file order.

    If track_id_filter is not None, only records whose track_id matches
    are yielded - everything else is skipped entirely (not written,
    not counted).
    """

    print(f"[Info] Loading .aemotevt log from {path}...")
    if track_id_filter is not None:
        print(f"[Info] Filtering to track_id == {track_id_filter} only, all other tracks will be dropped.")

    kept = 0
    skipped = 0

    with open(path, "rb") as f:
        header_bytes = f.read(AEMOTEVT_HEADER_SIZE)
        magic, version, _reserved, record_size, _reserved2 = struct.unpack(AEMOTEVT_HEADER_FMT, header_bytes)
        if magic != b"AEMOTEVT":
            raise ValueError(f"Unexpected magic bytes: {magic!r} - wrong file or format changed?")
        if record_size != AEMOTEVT_RECORD_SIZE:
            raise ValueError(
                f"record_size mismatch: header says {record_size}, "
                f"this script expects {AEMOTEVT_RECORD_SIZE} (version {version})."
            )

        while True:
            chunk = f.read(record_size)
            if len(chunk) < record_size:
                break
            t, track_id, x, y, p = struct.unpack(AEMOTEVT_RECORD_FMT, chunk)

            if track_id_filter is not None and track_id != track_id_filter:
                skipped += 1
                continue

            kept += 1
            yield t, x, y, p

    if track_id_filter is not None:
        print(f"[Info] Kept {kept} events for track_id {track_id_filter}, skipped {skipped} events from other tracks.")


def write_es_dvs(events, output_path, width, height):
    """events: iterable of (t_seconds, x, y, p) in non-decreasing t order.
    Writes an Event Stream v2 dvs file to output_path."""

    print(f"[Info] Converting .aemotevt log to .es format, saving to {output_path}...")

    with open(output_path, "wb") as f:
        f.write(ES_SIGNATURE)
        f.write(ES_VERSION)
        f.write(bytes([ES_TYPE_DVS]))
        f.write(struct.pack("<H", width))
        f.write(struct.pack("<H", height))

        previous_t_us = 0
        count = 0
        for t_seconds, x, y, p in events:
            t_us = round(t_seconds * 1e6)
            if t_us < previous_t_us:
                raise ValueError(
                    f"non-monotonic timestamp at event {count}: {t_us}us follows {previous_t_us}us "
                    f"- .es requires strictly non-decreasing timestamps (matches sepia.hpp's own check)"
                )
            if x >= width or y >= height:
                raise ValueError(
                    f"event {count} at ({x},{y}) is outside the declared {width}x{height} "
                    f"frame - .es readers will reject this (coordinates_overflow in sepia.hpp)"
                )

            relative_t = t_us - previous_t_us
            while relative_t >= MAX_DELTA_PER_BYTE:
                f.write(bytes([OVERFLOW_BYTE]))
                relative_t -= MAX_DELTA_PER_BYTE

            on_bit = 1 if p else 0
            f.write(bytes([(relative_t << 1) | on_bit]))
            f.write(struct.pack("<H", x))
            f.write(struct.pack("<H", y))

            previous_t_us = t_us
            count += 1

    return count


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="name of the .aemotevt raw-event log file inside the track_logs/ folder")
    parser.add_argument("--output", default=None, help="custom name to save the .es file to. Defaults to the same name as the input .aemotevt file")
    parser.add_argument("--width", type=int, default=1280, help="sensor width in pixels. Defaults to 1280 if not set")
    parser.add_argument("--height", type=int, default=720, help="sensor height in pixels. Defaults to 720 if not set")
    parser.add_argument("--track-id", type=int, required=True, help="only events with this track_id are written to the .es file - all other tracks are ignored")
    args = parser.parse_args()

    this_file_dir = os.path.dirname(os.path.abspath(__file__))
    aemotevt_path = os.path.join(this_file_dir, args.input + ".aemotevt")

    if args.output is None:
        output_path = os.path.join(this_file_dir, args.input + f"_track{args.track_id}.es")
    else:
        output_path = os.path.join(this_file_dir, args.output + ".es")

    n = write_es_dvs(
        read_aemotevt(aemotevt_path, track_id_filter=args.track_id),
        output_path,
        args.width,
        args.height,
    )
    print(f"Wrote {n} events (track_id {args.track_id} only) to {output_path} ({args.width}x{args.height}, dvs)")