
input_folder_path: "~/aemot_realtime"
input_data_name: "nan" ##unused

ref_image_ts_path: ""
process_ts_start: 0
process_ts_end: 100
event_num_start: -1
event_num_end: -1
width: 1281
height: 721

# width: 321
# height: 321

n_target: 4 # Default number of tracking target
data_format: 1 # 0: ts,c,r,p; 1: c,r,p,ts
ring_buffer_len: 10
dist_threshold: 10
publish_framerate: 40
contrast_threshold : 0.1
alpha: 50
m : 2 # Number of measurements
dt: 0.0001
n_state: 10 # Number of filter state


# Flags
use_gyro_flag: 0
save_video_flag: 0
save_image_flag: 0
save_track_flag: 0
disp_covariance_flag: 0
compute_TTC_flag: 0
print_TTC_flag: 0

select_target_flag: 2 # 0: predefined, 1: click to select, 2: detection

ref_image_ts_flag: 0


# Kalman filter
var_x: 30
var_y: 30   
var_vx: 50000 #was: 8000
var_vy: 50000 #was: 8000
var_lambda_1: 5
var_lambda_2: 5
var_theta: 0.5
var_q: 2
# q_x: 5000
# q_y: 5000
# q_vx: 40000
# q_vy: 40000
# q_lambda_1: 0.1
# q_lambda_2: 0.1
# q_theta: 0.005
# q_q: 0.01

q_x: 5000
q_y: 5000
q_vx: 40000
q_vy: 40000
q_lambda_1: 0.1
q_lambda_2: 0.1
q_theta: 0.005
q_q: 0.01

position_x_init: [328]
position_y_init: [408]
lambda_init: 25


# comms
comms_range: 10
decoder_thresh_on: 6
decoder_thresh_off: -6 
peak_thresh: 3.0
peak_win_size: 40
alpha_decoding: 8379 # (3334 / 2.5) * 2 * pi 
base_frequency: 3334 # 10000 / 3.0

flag_save_DI: 0
flag_save_G: 0


# Detector

f_show_candidates             : 1

# Line detector
SAE_ksize                     : 7
SAE_alpha                     : 3
SAE_operation_rate            : 200 # how many events between each operation
SAE_detection_threshold       : 0.75 # val = cos(theta)
SAE_min_active_pixels         : 10
SAE_min_contributions         : 12
SAE_min_detections_in_patch   : 40
MAX_NUMBER_OF_TRACKS          : 100

# Dt detection
detector_dist_threshold       : 50        # distance from existing track to allow detection
detector_dt_threshold         : 0.001 #0500  # maximum dt in sae patch around new event to detect led. 

# Evaluation parameters
f_evaluate                    : 1
evaluate_ts_age               : 0.3    # how long to wait before evaluating (let it get some events and initialise)
evaluate_dt_terminate         : 0.5     # time with no events before deleting 
evaluate_low_activity_factor  : 0.05     # factor of event rate threshold to delete track
event_rate_threshold          : 2000   # event rate required for validation


pool_size : 10