#!/usr/bin/env python3
"""
Code generated by Claude AI for this set up.

Crop a .es (Event Stream) file down to just its bottom-left quarter.


No dependencies beyond the Python standard library - this is a standalone
helper, not part of the C++ build.

Usage:
    python3 crop_es_bottom_left.py input.es output.es
"""
import sys

SIGNATURE = b"Event Stream"
VERSION = bytes([2, 0, 0])
TYPE_DVS = 1

    
def read_header(f):
    signature = f.read(len(SIGNATURE))
    if signature != SIGNATURE:
        raise ValueError("not a valid .es file (bad signature)")
    version = f.read(3)
    if version[0] != VERSION[0] or version[1] < VERSION[1]:
        raise ValueError(f"unsupported .es version {list(version)}")
    type_byte = f.read(1)[0]
    if type_byte != TYPE_DVS:
        raise ValueError(f"only DVS event streams are supported (got type byte {type_byte})")
    size_bytes = f.read(4)
    if len(size_bytes) < 4:
        raise ValueError("truncated header")
    width = size_bytes[0] | (size_bytes[1] << 8)
    height = size_bytes[2] | (size_bytes[3] << 8)
    return width, height


def write_header(f, width, height):
    f.write(SIGNATURE)
    f.write(VERSION)
    f.write(bytes([TYPE_DVS]))
    f.write(bytes([width & 0xFF, (width >> 8) & 0xFF, height & 0xFF, (height >> 8) & 0xFF]))


def read_events(f):
    """Yields (t, x, y, on) tuples; t is an absolute integer microsecond timestamp."""
    t = 0
    while True:
        b = f.read(1)
        if not b:
            return
        byte0 = b[0]
        if byte0 == 0b11111111:  # overflow marker: +127us, no event this byte
            t += 0b1111111
            continue
        if byte0 == 0b11111110:  # reserved no-op byte
            continue
        t += (byte0 >> 1)
        on = (byte0 & 1) == 1
        rest = f.read(4)
        if len(rest) < 4:
            return  # truncated file - stop cleanly rather than raising
        x = rest[0] | (rest[1] << 8)
        y = rest[2] | (rest[3] << 8)
        yield t, x, y, on


def write_event(f, t, x, y, on, previous_t):
    relative_t = t - previous_t
    if relative_t < 0:
        raise ValueError("timestamps must be non-decreasing")
    while relative_t >= 0b1111111:
        f.write(bytes([0b11111111]))
        relative_t -= 0b1111111
    byte0 = (relative_t << 1) | (1 if on else 0)
    f.write(bytes([byte0, x & 0xFF, (x >> 8) & 0xFF, y & 0xFF, (y >> 8) & 0xFF]))


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <input.es> <output.es>", file=sys.stderr)
        sys.exit(1)
    input_path, output_path = sys.argv[1], sys.argv[2]

    with open(input_path, "rb") as f_in:
        width, height = read_header(f_in)
        crop_width = width // 2
        crop_height = height // 2
        print(f"input: {width}x{height} -> keeping bottom-left {crop_width}x{crop_height}")

        kept = 0
        total = 0
        with open(output_path, "wb") as f_out:
            write_header(f_out, crop_width, crop_height)
            previous_t = 0
            for t, x, y, on in read_events(f_in):
                total += 1
                if x < crop_width and y >= crop_height:
                    write_event(f_out, t, x, y - crop_height, on, previous_t)
                    previous_t = t
                    kept += 1

    print(f"kept {kept} / {total} events -> {output_path}")


if __name__ == "__main__":
    main()