// TO BUILD: g++ -std=c++17 -O2 -I ../../gen4/common csv_to_es.cpp -o csv_to_es

// Code generated by Claude AI for this set up.
// Standalone CSV -> .es converter. Depends only on
// sepia.hpp (for sepia::dvs_event / sepia::write<type::dvs>)
//
// Usage:
//   csv_to_es <input.csv> <output.es> [options]
//
// Options:
//   --format 0|1     Column order per row. 0 (default): t,x,y,p
//                     1: x,y,p,t
//   --width W        Sensor width, for bounds-checking (default 1280)
//   --height H       Sensor height, for bounds-checking (default 720)
//   --has-header     Skip the first line of the CSV
//   --ts-scale S     Multiply the CSV timestamp column by S to get
//                     microseconds (default 1.0 - i.e. the CSV column is
//                     already in integer microseconds, matching sepia's
//                     native timestamp unit). E.g. pass 1e6 if your CSV
//                     timestamps are in seconds.
//   --sort           Sort events by timestamp before writing. The .es
//                     format requires non-decreasing timestamps; use this
//                     if your CSV isn't guaranteed to already be
//                     chronological. Without it, an out-of-order row
//                     aborts the conversion with an error telling you to
//                     add this flag.
//
// Polarity: any value > 0 in the p column is treated as ON, matching the
// convention used throughout the rest of this project (high_pass(), etc).

#include "sepia.hpp"

#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

struct csv_options {
    int format = 0;
    uint16_t width = 1280;
    uint16_t height = 720;
    bool has_header = false;
    double ts_scale = 1.0;
    bool sort = false;
};

std::vector<std::string> split_csv_line(const std::string& line) {
    std::vector<std::string> fields;
    std::stringstream stream(line);
    std::string field;
    while (std::getline(stream, field, ',')) {
        fields.push_back(field);
    }
    return fields;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "usage: " << argv[0] << " <input.csv> <output.es> [options]\n"
                  << "  --format 0|1     column order: 0 = t,x,y,p (default), 1 = x,y,p,t\n"
                  << "  --width W        sensor width (default 1280)\n"
                  << "  --height H       sensor height (default 720)\n"
                  << "  --has-header     skip the first CSV line\n"
                  << "  --ts-scale S     multiply the timestamp column by S to get microseconds "
                     "(default 1.0)\n"
                  << "  --sort           sort events by timestamp before writing\n";
        return 1;
    }
    const std::string csv_path = argv[1];
    const std::string es_path = argv[2];

    csv_options options;
    for (int i = 3; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--format" && i + 1 < argc) {
            options.format = std::stoi(argv[++i]);
        } else if (arg == "--width" && i + 1 < argc) {
            options.width = static_cast<uint16_t>(std::stoi(argv[++i]));
        } else if (arg == "--height" && i + 1 < argc) {
            options.height = static_cast<uint16_t>(std::stoi(argv[++i]));
        } else if (arg == "--has-header") {
            options.has_header = true;
        } else if (arg == "--ts-scale" && i + 1 < argc) {
            options.ts_scale = std::stod(argv[++i]);
        } else if (arg == "--sort") {
            options.sort = true;
        } else {
            std::cerr << "unrecognised option: " << arg << "\n";
            return 1;
        }
    }

    std::ifstream csv_file(csv_path);
    if (!csv_file.is_open()) {
        std::cerr << "could not open " << csv_path << "\n";
        return 1;
    }

    // Parse the whole file into memory first: needed for --sort anyway, and
    // simplifies giving a clean error with the CSV row number before any
    // bytes are written to the output file.
    std::vector<sepia::dvs_event> events;
    std::string line;
    std::size_t row_number = 0;
    std::size_t skipped_rows = 0;
    if (options.has_header && std::getline(csv_file, line)) {
        ++row_number;
    }
    while (std::getline(csv_file, line)) {
        ++row_number;
        if (line.empty()) {
            continue;
        }
        const auto fields = split_csv_line(line);
        if (fields.size() < 4) {
            std::cerr << "row " << row_number << ": expected 4 columns, got " << fields.size()
                      << " - skipping\n";
            ++skipped_rows;
            continue;
        }
        try {
            double ts_raw;
            int x, y, p;
            if (options.format == 0) {
                ts_raw = std::stod(fields[0]);
                x = std::stoi(fields[1]);
                y = std::stoi(fields[2]);
                p = std::stoi(fields[3]);
            } else {
                x = std::stoi(fields[0]);
                y = std::stoi(fields[1]);
                p = std::stoi(fields[2]);
                ts_raw = std::stod(fields[3]);
            }
            if (x < 0 || y < 0 || x >= options.width || y >= options.height) {
                std::cerr << "row " << row_number << ": (" << x << "," << y
                          << ") out of bounds for " << options.width << "x" << options.height
                          << " - skipping\n";
                ++skipped_rows;
                continue;
            }
            sepia::dvs_event event{};
            event.t = static_cast<uint64_t>(ts_raw * options.ts_scale);
            event.x = static_cast<uint16_t>(x);
            event.y = static_cast<uint16_t>(y);
            event.on = (p > 0);
            events.push_back(event);
        } catch (const std::exception& error) {
            std::cerr << "row " << row_number << ": could not parse (" << error.what() << ") - skipping\n";
            ++skipped_rows;
        }
    }

    if (events.empty()) {
        std::cerr << "no valid events parsed from " << csv_path << "\n";
        return 1;
    }

    if (options.sort) {
        std::stable_sort(events.begin(), events.end(), [](const sepia::dvs_event& a, const sepia::dvs_event& b) {
            return a.t < b.t;
        });
    }

    auto output_stream = std::make_unique<std::ofstream>(es_path, std::ios::binary);
    if (!output_stream->is_open()) {
        std::cerr << "could not open " << es_path << " for writing\n";
        return 1;
    }

    try {
        sepia::write<sepia::type::dvs> write(std::move(output_stream), options.width, options.height);
        for (std::size_t i = 0; i < events.size(); ++i) {
            write(events[i]);
        }
    } catch (const std::logic_error& error) {
        std::cerr << "error: " << error.what()
                  << "\nThe .es format requires non-decreasing timestamps. Re-run with --sort if your "
                     "CSV isn't already chronological.\n";
        return 1;
    } catch (const std::exception& error) {
        std::cerr << "error writing " << es_path << ": " << error.what() << "\n";
        return 1;
    }

    std::cout << "wrote " << events.size() << " events to " << es_path;
    if (skipped_rows > 0) {
        std::cout << " (" << skipped_rows << " rows skipped, see warnings above)";
    }
    std::cout << "\n";

    return 0;
}