// BUILD: g++ -std=c++17 -O2 $(pkg-config --cflags libusb-1.0) camera_driver.cpp processing.cpp -o main_sys $(pkg-config --libs libusb-1.0) -lpthread

// Code generated by Claude AI for this setup.

#include "evk4.hpp" // pulls in camera.hpp, psee.hpp and sepia.hpp too

#include "event_queue.hpp"
#include "processing.hpp"

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <iostream>
#include <thread>

std::atomic<bool> running{true};

void handle_sigint(int) {
    running.store(false);
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "usage: " << argv[0] << " <config_name>\n";
        std::cerr << "  (config_name is looked up as configs/<config_name>.yaml by processing::setup)\n";
    }
    const std::string config_name = (argc > 1) ? argv[1] : "default";

    std::cout << "Loading: configs/" << config_name << ".yaml...\n";

    std::signal(SIGINT, handle_sigint);

    sepia::usb::device_properties device{0, "", sepia::usb::device_speed::unknown};
    auto found = false;
    for (const auto& available_device : sepia::psee::available_devices()) {
        if (available_device.type == sepia::psee::EVK4) {
            device = available_device;
            found = true;
            break;
        }
    }
    if (!found) {
        std::cerr << "no EVK4 connected\n";
        return 1;
    }
    std::cout << "opening EVK4 " << device.serial << "\n";

    // Bounded to 256 pending batches. Tune this: bigger absorbs longer
    // stalls in your processing thread before dropping data, at the cost
    // of more latency and memory when it's backed up.
    event_queue queue(256);

    // Worker thread: this is the ONLY thread that calls into your
    // processing code, so process_batch never needs to worry about
    // concurrent calls.
    std::thread worker([&]() {
        if (!processing::setup(config_name)) {
            std::cerr << "processing setup failed, aborting\n";
            running.store(false);
            return;
        }
        std::vector<sepia::dvs_event> batch;
        while (queue.pop(batch)) {
            processing::process_batch(batch);
        }
        processing::teardown();
    });

    // Accumulates events for the current USB packet. Captured by
    // reference in the lambdas below; cleared and handed off in
    // after_buffer.
    std::vector<sepia::dvs_event> current_batch;
    current_batch.reserve(4096);

    auto before_buffer = [&](std::size_t fifo_used, std::size_t fifo_size) {
        (void)fifo_used;
        (void)fifo_size;
        return true;
    };

    // Runs once per USB packet, after all of its events have been
    // dispatched to handle_event. Hand the accumulated batch to the
    // queue and start a fresh one.
    auto after_buffer = [&]() {
        if (!current_batch.empty()) {
            queue.push(std::move(current_batch));
            current_batch.clear();
            current_batch.reserve(4096);
        }
    };

    auto handle_trigger_event = [&](sepia::evk4::trigger_event event) { (void)event; };

    // Runs on the camera's decode thread, for every event. Keep this to
    // "append to the batch" - nothing heavier.
    auto handle_event = [&](sepia::dvs_event event) { current_batch.push_back(event); };

    auto handle_exception = [&](std::exception_ptr exception) {
        try {
            std::rethrow_exception(exception);
        } catch (const std::exception& error) {
            std::cerr << "camera error: " << error.what() << "\n";
        }
        running.store(false);
    };

    auto camera = sepia::evk4::make_camera(
        handle_event,
        handle_trigger_event,
        before_buffer,
        after_buffer,
        handle_exception,
        sepia::evk4::default_parameters,
        device.serial,
        std::chrono::milliseconds(100),
        128,   // buffers_count
        16384, // fifo_size
        []() { std::cerr << "warning: packet dropped\n"; });

    while (running.load()) {
        std::this_thread::sleep_for(std::chrono::seconds(1));
        std::cout << "queue dropped " << queue.dropped_batches() << "/" << queue.pushed_batches() << " batches so far\n";
        //std::cout << "queue pushed " << queue.pushed_batches() << " batches total\n";
    }

    // Stop the camera first (destructor joins its threads and stops
    // calling handle_event/after_buffer), THEN stop the queue so the
    // worker thread finishes draining whatever's left and exits cleanly.
    camera.reset();
    queue.stop();
    worker.join();

    return 0;
}