// Code generated by Claude AI for this setup.
// Drop-in replacement for the live-camera ingestion in main.cpp: reads
// events from a .es file instead of a physical EVK4, batches them the same
// way, and pushes them onto the same event_queue - so processing.cpp,
// TrackManager, and KalmanFilter are all completely unchanged.
//
// Unlike the live camera path (which drops the oldest batch under load,
// since staleness matters more than completeness for a live feed), this
// uses event_queue::push_blocking(): it waits for room instead of
// dropping, so replay never loses a single event. It just runs only as
// fast as processing.cpp is actually able to keep up with - slower than
// real-time if it has to be.

#include "sepia.hpp"

#include "event_queue.hpp"
#include "processing.hpp"

#include <atomic>
#include <condition_variable>
#include <csignal>
#include <fstream>
#include <future>
#include <iostream>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

std::atomic<bool> running{true};

void handle_sigint(int) {
    running.store(false);
}

struct replay_cancelled : std::exception {
    const char* what() const noexcept override { return "replay cancelled"; }
};

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "usage: " << argv[0] << " <config_name> <events.es>\n";
        return 1;
    }
    const std::string config_name = argv[1];
    const std::string es_path = argv[2];

    std::cout << "Loading: configs/" << config_name << ".yaml...\n";

    std::signal(SIGINT, handle_sigint);

    // Same queue type, same bound, as the live camera path
    event_queue queue(256);
    frame_queue frames(3);
    std::promise<bool> setup_promise;

    // Same worker-thread pattern as camera_driver.cpp: this is the only thread that calls into processing:: code.
    std::thread worker([&]() {
        const bool ok = processing::setup(config_name, frames);
        setup_promise.set_value(ok);
        if (!ok) {
            std::cerr << "processing setup failed, aborting\n";
            running.store(false);
            return;
        }
        std::vector<sepia::dvs_event> batch;
        while (queue.pop(batch)) {
            processing::process_batch(batch);
        }
        processing::teardown();
    });

    if (!setup_promise.get_future().get()) {
        queue.stop();
        worker.join();
        return 1;
    }

    // seperate thread for the renderer, so that it can run at its own pace and not block the processing thread
    std::thread render_thread([&]() {
        processing::render_setup();
        frame_job job;
        while (frames.pop(job)) {
            if (processing::render_frame(job)) { // if the user pressed ESC, signal to stop the main loop and break out of the render loop
                running.store(false);
                break;
            }
        }
        processing::render_teardown();
    });

    std::signal(SIGINT, handle_sigint);

    // Accumulates events read from the file into fixed-size batches before
    // handing them to the queue, mirroring how the live camera batches
    // events per USB packet. There's no natural "packet boundary" when
    // reading a file, so this just batches by a fixed event count instead.
    constexpr std::size_t batch_size = 4096;
    std::vector<sepia::dvs_event> current_batch;
    current_batch.reserve(batch_size);

    // Signalled once the file has been fully read (or a real read error
    // occurred) so main() knows when it's safe to stop the queue.
    std::mutex done_mutex;
    std::condition_variable done_cv;
    bool reading_done = false;

    // Runs on the observable's own internal read thread, one event at a
    // time. push_blocking() here is what provides the backpressure: if the
    // queue is full, this call - and therefore the whole read thread -
    // simply waits, pausing file reading until processing catches up.
    auto handle_event = [&](sepia::dvs_event event) {
        if (!running.load()) {
            throw replay_cancelled{};
        }
        current_batch.push_back(event);
        if (current_batch.size() >= batch_size) {
            queue.push_blocking(std::move(current_batch));
            current_batch.clear();
            current_batch.reserve(batch_size);
        }
    };

    // The observable throws sepia::end_of_file when the stream runs out -
    // that's the expected, normal way this loop ends, not an error.
    auto handle_exception = [&](std::exception_ptr exception) {
        try {
            std::rethrow_exception(exception);
        } catch (const sepia::end_of_file&) {
            // normal end of the recording
        } catch (const replay_cancelled&) {
            // user hit Ctrl+C - not an error, just stop reading
        } catch (const std::exception& error) {
            std::cerr << "replay error: " << error.what() << "\n";
        }
        // Flush whatever's left in the partial trailing batch - the file
        // ending mid-batch must not silently drop those last events.
        if (!current_batch.empty()) {
            queue.push_blocking(std::move(current_batch));
            current_batch.clear();
        }
        {
            std::lock_guard<std::mutex> lock(done_mutex);
            reading_done = true;
        }
        done_cv.notify_all();
    };

    auto event_stream = std::make_unique<std::ifstream>(es_path, std::ios::binary);
    if (!event_stream->is_open()) {
        std::cerr << "could not open " << es_path << "\n";
        running.store(false);
        queue.stop();
        worker.join();
        frames.stop();
        render_thread.join();
        return 1;
    }

    // as_fast_as_possible: no real-time pacing at all - read and dispatch
    // events as quickly as the (blocking) queue push allows.
    auto observable = sepia::make_observable<sepia::type::dvs>(
        std::move(event_stream),
        handle_event,
        handle_exception,
        &sepia::false_function, // don't loop back to the start of the file
        sepia::dispatch::as_fast_as_possible,
        1 << 16);

    // Wait for the file to finish (or Ctrl+C).
    {
        std::unique_lock<std::mutex> lock(done_mutex);
        while (!reading_done && running.load()) {
            done_cv.wait_for(lock, std::chrono::milliseconds(100), [&] { return reading_done; });
        }
    }
    observable.reset(); // stops and joins the observable's own read thread

    // Let the worker fully drain whatever's still queued (there may still
    // be up to `queue`'s capacity worth of batches waiting), then shut down.
    queue.stop();
    worker.join();
    frames.stop();
    render_thread.join();

    return 0;
}