#pragma once

#include "frame_queue.hpp"
#include "sepia.hpp"

#include <string>
#include <vector>

// Code generated by Claude AI for this set up.

namespace processing {

    // Loads `config_name`.yaml and allocates all per-run state (Kalman
    // filter templates, track manager, SAE detector, display buffers,
    // OpenCV window). Must be called exactly once, before the first
    // process_batch() call, from the SAME thread that will call
    // process_batch() - OpenCV's HighGUI calls (namedWindow / imshow /
    // waitKey) are not safe to spread across multiple threads, so both
    // functions being on the one thread is intentional, not an oversight.
    //
    // Returns false if the config could not be loaded. Callers MUST check
    // this and not call process_batch() if it returns false - track_manager
    // and detector are left null in that case.
    bool setup(const std::string& config_name, frame_queue& frames);

    // Called once per batch of events pulled off the camera queue, in
    // order, one batch at a time, on the same thread that called setup().
    // Feeds every event through the tracker, and - at most once every
    // 1/params.publish_framerate seconds of *event* time, matching the
    // original offline pipeline's behaviour - refreshes the display/video output.
    void process_batch(const std::vector<sepia::dvs_event>& events);

    // Called once after the camera stops (on the same thread as setup()/
    // process_batch()). Releases the video writer and reports totals.
    void teardown();


    // ---- Render thread: all OpenCV GUI/video-writer calls live here ----
    //
    // These three must all run on the SAME thread as each other (a
    // dedicated render thread, separate from the one running setup()/
    // process_batch()/teardown() above) - and that thread must not be the
    // one running process_batch(), or you're back to blocking event
    // processing on frame rendering. render_setup() must not be called
    // until setup() (above) has already returned true, since it reads
    // config state (params/dispParams) setup() loaded.
 
    // Opens the display window and video writer (if configured), and
    // renders the initial empty frame - the render-thread equivalent of
    // what setup() used to do directly.
    void render_setup();
 
    // Draws and optionally saves/writes one frame from a self-contained
    // snapshot - never reads shared tracking state directly.
    bool render_frame(const frame_job& job);
 
    // Releases the video writer and destroys the window.
    void render_teardown();


} // namespace processing