#pragma once

#include "../../gen4/common/sepia.hpp"

#include <string>
#include <vector>

// Code generated by Claude AI for this set up.

namespace processing {

    // Loads `config_name`.yaml and allocates all per-run state (Kalman
    // filter templates, track manager, SAE detector, display buffers,
    // OpenCV window). Must be called exactly once, before the first
    // process_batch() call, from the SAME thread that will call
    // process_batch() - OpenCV's HighGUI calls (namedWindow / imshow /
    // waitKey) are not safe to spread across multiple threads, so both
    // functions being on the one thread is intentional, not an oversight.
    //
    // Returns false if the config could not be loaded. Callers MUST check
    // this and not call process_batch() if it returns false - track_manager
    // and detector are left null in that case.
    bool setup(const std::string& config_name);

    // Called once per batch of events pulled off the camera queue, in
    // order, one batch at a time, on the same thread that called setup().
    // Feeds every event through the tracker, and - at most once every
    // 1/params.publish_framerate seconds of *event* time, matching the
    // original offline pipeline's behaviour - refreshes the display/video output.
    void process_batch(const std::vector<sepia::dvs_event>& events);

    // Called once after the camera stops (on the same thread as setup()/
    // process_batch()). Releases the video writer and reports totals.
    void teardown();

} // namespace processing