#pragma once

#include <chrono>
#include <iostream>
#include <string>
#include <unordered_map>

// Code generated by Claude AI for this set up.
// ---------------------------------------------------------------------------
// Minimal accumulating profiler: wrap a code region in AEMOT_TIMED_SCOPE(name)
// and every call's duration gets summed into a global table, keyed by name.
// Call Profiler::report() once at teardown to print totals + call counts +
// average per call for every named region.
//
// Deliberately NOT using this for every tiny line - std::chrono::now() itself
// costs ~20-100ns per call, so wrapping something sub-microsecond will mostly
// measure the timer's own overhead, not real work. Use this around whole
// logical stages (the association loop, one evaluate*() call, one log()
// call, one detector call) - not individual arithmetic lines.
//
// Single-threaded assumption: this is meant for the processing thread's
// per-event hot loop. If you also want to profile the render or writer
// threads, give them their own Profiler instance (or add a mutex here) -
// as-is this is NOT thread-safe.
// ---------------------------------------------------------------------------
class Profiler {
public:
    struct Region {
        uint64_t calls = 0;
        double total_seconds = 0.0;
    };

    static Profiler& instance() {
        static Profiler p;
        return p;
    }

    void add(const std::string& name, double seconds) {
        auto& r = regions_[name];
        r.calls++;
        r.total_seconds += seconds;
    }

    void report() const {
        std::cout << "\n---- Profiler report ----\n";
        double grand_total = 0.0;
        for (const auto& [name, r] : regions_) grand_total += r.total_seconds;

        for (const auto& [name, r] : regions_) {
            double pct = grand_total > 0 ? (100.0 * r.total_seconds / grand_total) : 0.0;
            double avg_us = r.calls > 0 ? (r.total_seconds * 1e6 / r.calls) : 0.0;
            std::cout << name << ": " << r.total_seconds << "s total, "
                      << r.calls << " calls, " << avg_us << "us/call avg, "
                      << pct << "% of measured time\n";
        }
        std::cout << "-------------------------\n";
    }

private:
    std::unordered_map<std::string, Region> regions_;
};

class ScopedTimer {
public:
    explicit ScopedTimer(const std::string& name)
        : name_(name), start_(std::chrono::steady_clock::now()) {}

    ~ScopedTimer() {
        auto end = std::chrono::steady_clock::now();
        double seconds = std::chrono::duration<double>(end - start_).count();
        Profiler::instance().add(name_, seconds);
    }

private:
    std::string name_;
    std::chrono::steady_clock::time_point start_;
};

#define AEMOT_CONCAT_(a, b) a##b
#define AEMOT_CONCAT(a, b) AEMOT_CONCAT_(a, b)
#define AEMOT_TIMED_SCOPE(name) ScopedTimer AEMOT_CONCAT(_aemot_timer_, __COUNTER__)(name)
