#pragma once

#include <condition_variable>
#include <cstdint>
#include <deque>
#include <fstream>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

// Code generated by Claude AI for this set up.
// ---------------------------------------------------------------------------
// Binary log record for one Kalman state update.
//
// Deliberately minimal (track_id + ts + state vector only, no covariance) to
// keep records small and the memcpy on the hot path cheap - this is written
// on every associated event, for every active track. If you need covariance
// too, add `double P_diag[10]` (or the full 10x10) here - the rest of the
// design (buffering, writer thread) doesn't change, just the record size and
// the memcpy length in log().
//
// No #pragma pack needed: track_id(8) + ts(8) + x_hat(8*8=64) are all
// naturally 8-byte aligned already, so the compiler won't insert padding -
// sizeof(KalmanLogRecord) == 80 on any common platform.
// ---------------------------------------------------------------------------
struct KalmanLogRecord {
    uint64_t track_id;
    double   ts;
    double   x_hat[8]; // now dropped to 8 to remove dead weight. Doesn't match kalmanFilter::N_state anymore

    static constexpr int N_STATE = 8;
};

// Small self-describing header written once at the start of the file, so a
// reader doesn't need to know the record layout out of band.
struct KalmanLogFileHeader {
    char     magic[8] = {'A', 'E', 'M', 'O', 'T', 'L', 'O', 'G'};
    uint32_t version = 2; // v2: bumped x_hat width changed from 10 to 8
    uint32_t n_state = KalmanLogRecord::N_STATE;
    uint32_t record_size = sizeof(KalmanLogRecord);
    uint32_t reserved = 0;
};
// sizeof(KalmanLogFileHeader) == 24 bytes - also a multiple of 8, so the
// first record after it stays 8-byte aligned in the file too.

// ---------------------------------------------------------------------------
// Appends KalmanLogRecord entries to a single binary file as fast as
// possible, off the calling thread.
//
// Threading model:
//   - log() is intended to be called from ONE thread only - the processing
//     thread, right after KalmanFilter::update() (or track creation). It is
//     NOT safe to call from multiple threads concurrently. It doesn't need
//     to be: KalmanFilter::update() already only ever runs on the single
//     processing thread in this codebase, so every state change is already
//     serialized in call order before it reaches this class - different
//     tracks updating at the same-ish time just means their records end up
//     interleaved in the file in the order their updates actually happened,
//     which is exactly what you want for reconstruction.
//   - On the hot path, log() only appends to an in-memory buffer
//     (std::vector::push_back on a pre-reserved buffer - no allocation, no
//     syscall, no locking).
//   - When a buffer fills, it's handed off (by pointer, no copy) to a
//     bounded queue drained by a dedicated writer thread, which does the
//     actual file I/O. A small pool of pre-allocated buffers circulates back
//     from the writer thread so the hot path never allocates after startup.
//   - If the writer thread falls behind and the free-buffer pool is
//     exhausted, log() blocks briefly waiting for a buffer rather than
//     dropping data - this log is meant to be complete, unlike the
//     frame-publishing path elsewhere in this codebase which is fine to
//     drop stale frames.
// ---------------------------------------------------------------------------
class TrackLogger {
public:
    // buffer_capacity_records: records per buffer before it's flushed
    //   (default 8192 -> ~768KB per flush, a good size for sequential
    //   write throughput without excessive memory use).
    // num_buffers: how many buffers circulate between producer and writer
    //   (default 4 -> ~3MB total, absorbs bursts of ~32k events before
    //   log() would ever have to wait on the writer thread).
    // Throws std::runtime_error if output_path can't be opened for writing.
    explicit TrackLogger(const std::string& output_path,
                          size_t buffer_capacity_records = 8192,
                          int num_buffers = 4);
    ~TrackLogger();

    TrackLogger(const TrackLogger&) = delete;
    TrackLogger& operator=(const TrackLogger&) = delete;

    // Appends one record. x_hat_data must point to at least
    // KalmanLogRecord::N_STATE contiguous doubles (e.g. from
    // KalmanFilter::state_data()).
    void log(uint64_t track_id, double ts, const double* x_hat_data);

    // Flushes any partially-filled buffer and stops the writer thread.
    // Safe to call once; the destructor calls this too if not already done.
    // Call this from teardown() so buffered-but-unflushed records aren't
    // lost on normal shutdown.
    void close();

private:
    void writer_thread_main();
    void enqueue_current_buffer();      // hands off current_buffer_, blocks acquiring a fresh one
    std::vector<KalmanLogRecord>* acquire_free_buffer(); // blocks if none available

    std::string output_path_;
    size_t buffer_capacity_records_;
    int num_buffers_;

    std::vector<std::vector<KalmanLogRecord>*> owned_buffers_; // for cleanup only
    std::vector<KalmanLogRecord>* current_buffer_ = nullptr;   // touched by producer thread only

    std::mutex queue_mutex_;
    std::condition_variable queue_cv_;
    std::deque<std::vector<KalmanLogRecord>*> filled_queue_;
    std::deque<std::vector<KalmanLogRecord>*> free_queue_;
    bool stopping_ = false;

    std::thread writer_thread_;
    bool closed_ = false;
};
