#pragma once

#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>

// Code generated by Claude AI for this set up.
// ---------------------------------------------------------------------------
// Per-track summary log: one record per *validated* track, written once at
// validation-time-of-death (deletion, or program shutdown while still
// active). This is a companion to track_logger.hpp's per-event log, not a
// replacement - the per-event log gives you the full state trajectory, this
// gives you the covariance at the two points that matter for offline
// tracklet stitching (validation and end-of-life), which the per-event log
// deliberately never stores.
//
// Kept as a separate file/format from the per-event log because these
// records are a completely different shape (much bigger, much rarer) Written synchronously
// on the processing thread (same single-writer-thread rule as TrackLogger),
// no buffering needed: summaries happen per-track, not per-event, so the
// write volume is orders of magnitude lower and doesn't justify the
// double-buffer/writer-thread machinery TrackLogger uses.
// ---------------------------------------------------------------------------

// Bitmask reasons a track's summary was written. Multiple bits can be set
// (e.g. a track can be both out-of-frame AND inactive simultaneously).
namespace TrackDeleteReason {
    constexpr uint32_t OUT_OF_FRAME              = 1u << 0;
    constexpr uint32_t INACTIVE                  = 1u << 1;
    constexpr uint32_t LOW_ACTIVITY               = 1u << 2;
    constexpr uint32_t BAD_SHAPE                  = 1u << 3;
    constexpr uint32_t DUPLICATE_TRACK            = 1u << 4;
    constexpr uint32_t STILL_ACTIVE_AT_SHUTDOWN   = 1u << 5; // never "deleted" - flushed at teardown instead
}

// State/covariance are trimmed to the first 8 elements of the 10-wide
// x_hat/P used elsewhere - indices 8 and 9 are the currently-unused
// reserved state slots, so there's no information lost by dropping them here.
inline constexpr int kSummaryStateDim = 8;

struct TrackSummaryRecord {
    uint64_t track_id;

    double   t_created;    // kf->get_t0()
    double   t_validated;  // ts at the moment validated flipped to 1
    double   t_deleted;    // kf->get_ts_last() at the moment of deletion/shutdown

    uint32_t num_records;    // how many per-event records this track has in the main .bees log
    uint32_t delete_reason;  // bitmask, see TrackDeleteReason above

    double   event_rate_at_deletion; // 1.0 / dt_moving_avg at time of writing

    double   x_hat_at_validation[kSummaryStateDim];
    double   P_at_validation[kSummaryStateDim * kSummaryStateDim];  // row-major, symmetric

    double   x_hat_at_deletion[kSummaryStateDim];
    double   P_at_deletion[kSummaryStateDim * kSummaryStateDim];    // row-major, symmetric
};
// All groupings above land on 8-byte boundaries (the two uint32_t fields
// are paired together), so this is naturally aligned with no compiler
// padding - sizeof(TrackSummaryRecord) == 1200 on any common platform.

struct TrackSummaryFileHeader {
    char     magic[8] = {'A', 'E', 'M', 'O', 'T', 'S', 'U', 'M'}; // "AEMOTSUM" - distinct from the per-event log's magic
    uint32_t version = 1;
    uint32_t state_dim = kSummaryStateDim;
    uint32_t record_size = sizeof(TrackSummaryRecord);
    uint32_t reserved = 0;
};
// sizeof(TrackSummaryFileHeader) == 24 - same shape as KalmanLogFileHeader,
// so the same "read header, then fixed-stride records" logic applies.

// ---------------------------------------------------------------------------
// Minimal synchronous writer - intentionally simpler than TrackLogger.
// Summaries are written at most a few times per few hundred events (once
// per validated track, at deletion or shutdown), so there's no hot-path
// pressure that would justify TrackLogger's buffer pool + writer thread.
// Like TrackLogger, log() must only ever be called from the processing
// thread - deleteTrack() (where this gets called from) already only runs
// there.
// ---------------------------------------------------------------------------
class TrackSummaryLogger {
public:
    // Throws std::runtime_error if output_path can't be opened for writing.
    explicit TrackSummaryLogger(const std::string& output_path);
    ~TrackSummaryLogger();

    TrackSummaryLogger(const TrackSummaryLogger&) = delete;
    TrackSummaryLogger& operator=(const TrackSummaryLogger&) = delete;

    void log(const TrackSummaryRecord& record);

    // Flushes and closes the file. Safe to call once; destructor calls this
    // too if not already done. Call explicitly from teardown() so the OS
    // buffer is flushed before shutdown.
    void close();

private:
    std::ofstream file_;
    bool closed_ = false;
};