#include "track_summary_logger.hpp"

#include <stdexcept>

// Code generated by Claude AI for this set up.
TrackSummaryLogger::TrackSummaryLogger(const std::string& output_path) {
    file_.open(output_path, std::ios::binary | std::ios::trunc);
    if (!file_.is_open()) {
        throw std::runtime_error("[TrackSummaryLogger]: could not open output file: " + output_path);
    }

    TrackSummaryFileHeader header;
    file_.write(reinterpret_cast<const char*>(&header), sizeof(header));
}

TrackSummaryLogger::~TrackSummaryLogger() {
    close();
}

void TrackSummaryLogger::log(const TrackSummaryRecord& record) {
    if (closed_ || !file_.is_open()) return;
    file_.write(reinterpret_cast<const char*>(&record), sizeof(record));
}

void TrackSummaryLogger::close() {
    if (closed_) return;
    closed_ = true;
    if (file_.is_open()) {
        file_.flush();
        file_.close();
    }
}