#include "track_logger.hpp"

#include <cstring>
#include <stdexcept>

// code generated by Claude AI for this set up.
TrackLogger::TrackLogger(const std::string& output_path,
                          size_t buffer_capacity_records,
                          int num_buffers)
    : output_path_(output_path),
      buffer_capacity_records_(buffer_capacity_records),
      num_buffers_(num_buffers)
{
    // Fail fast if the path is bad
    {
        std::ofstream test(output_path_, std::ios::binary | std::ios::trunc);
        if (!test.is_open()) {
            throw std::runtime_error("[TrackLogger]: could not open output file: " + output_path_);
        }
    }

    // Pre-allocate every buffer up front
    owned_buffers_.reserve(num_buffers_);
    for (int i = 0; i < num_buffers_; ++i) {
        auto* buf = new std::vector<KalmanLogRecord>();
        buf->reserve(buffer_capacity_records_);
        owned_buffers_.push_back(buf);
        if (i == 0) {
            current_buffer_ = buf;
        } else {
            free_queue_.push_back(buf);
        }
    }

    writer_thread_ = std::thread(&TrackLogger::writer_thread_main, this);
}

TrackLogger::~TrackLogger() {
    close();
    for (auto* buf : owned_buffers_) {
        delete buf;
    }
}

void TrackLogger::log(uint64_t track_id, double ts, const double* x_hat_data) {
    KalmanLogRecord rec;
    rec.track_id = track_id;
    rec.ts = ts;
    std::memcpy(rec.x_hat, x_hat_data, sizeof(rec.x_hat));

    current_buffer_->push_back(rec);

    if (current_buffer_->size() >= buffer_capacity_records_) {
        enqueue_current_buffer();
    }
}

void TrackLogger::enqueue_current_buffer() {
    {
        std::lock_guard<std::mutex> lock(queue_mutex_);
        filled_queue_.push_back(current_buffer_);
    }
    queue_cv_.notify_all(); // wake the writer thread
    current_buffer_ = acquire_free_buffer(); // blocks only if the writer is genuinely behind
}

std::vector<KalmanLogRecord>* TrackLogger::acquire_free_buffer() {
    std::unique_lock<std::mutex> lock(queue_mutex_);
    queue_cv_.wait(lock, [&] { return !free_queue_.empty(); });
    auto* buf = free_queue_.front();
    free_queue_.pop_front();
    return buf;
}

void TrackLogger::writer_thread_main() {
    std::ofstream file(output_path_, std::ios::binary | std::ios::trunc);

    if (!file.is_open()) {
        return;
    }

    KalmanLogFileHeader header;
    file.write(reinterpret_cast<const char*>(&header), sizeof(header));

    while (true) {
        std::vector<KalmanLogRecord>* buf = nullptr;
        {
            std::unique_lock<std::mutex> lock(queue_mutex_);
            queue_cv_.wait(lock, [&] { return !filled_queue_.empty() || stopping_; });
            if (filled_queue_.empty() && stopping_) {
                break; // nothing left to drain, and no more will arrive
            }
            buf = filled_queue_.front();
            filled_queue_.pop_front();
        }

        if (!buf->empty()) {
            // One large sequential write per buffer (~768KB by default)
            file.write(reinterpret_cast<const char*>(buf->data()),
                       static_cast<std::streamsize>(buf->size() * sizeof(KalmanLogRecord)));
            buf->clear(); // keep the reserved capacity for reuse
        }

        {
            std::lock_guard<std::mutex> lock(queue_mutex_);
            free_queue_.push_back(buf);
        }
        queue_cv_.notify_all(); // wake the producer if it's waiting for a free buffer
    }

    file.flush();
    file.close();
}

void TrackLogger::close() {
    if (closed_) return;
    closed_ = true;

    // Flush whatever's left in the current (possibly partially-filled)
    // buffer so normal shutdown doesn't lose the last few records.
    if (current_buffer_ != nullptr) {
        std::lock_guard<std::mutex> lock(queue_mutex_);
        if (!current_buffer_->empty()) {
            filled_queue_.push_back(current_buffer_);
        } else {
            free_queue_.push_back(current_buffer_); // nothing to flush, just return it
        }
        current_buffer_ = nullptr;
    }

    {
        std::lock_guard<std::mutex> lock(queue_mutex_);
        stopping_ = true;
    }
    queue_cv_.notify_all();

    if (writer_thread_.joinable()) {
        writer_thread_.join();
    }
}
